[2025-06-17T18:17:15.229+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-17T18:17:15.252+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_csv_to_hive.spark_ingest manual__2025-06-17T18:17:14.938974+00:00 [queued]>
[2025-06-17T18:17:15.259+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_csv_to_hive.spark_ingest manual__2025-06-17T18:17:14.938974+00:00 [queued]>
[2025-06-17T18:17:15.261+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-06-17T18:17:15.275+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): spark_ingest> on 2025-06-17 18:17:14.938974+00:00
[2025-06-17T18:17:15.283+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=726) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-17T18:17:15.284+0000] {standard_task_runner.py:72} INFO - Started process 727 to run task
[2025-06-17T18:17:15.283+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ingest_csv_to_hive', 'spark_ingest', 'manual__2025-06-17T18:17:14.938974+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/ETL_flow.py', '--cfg-path', '/tmp/tmp0pbf4yt7']
[2025-06-17T18:17:15.285+0000] {standard_task_runner.py:105} INFO - Job 14: Subtask spark_ingest
[2025-06-17T18:17:15.310+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-17T18:17:15.353+0000] {task_command.py:467} INFO - Running <TaskInstance: ingest_csv_to_hive.spark_ingest manual__2025-06-17T18:17:14.938974+00:00 [running]> on host b11ca03b7444
[2025-06-17T18:17:15.444+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_csv_to_hive' AIRFLOW_CTX_TASK_ID='spark_ingest' AIRFLOW_CTX_EXECUTION_DATE='2025-06-17T18:17:14.938974+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-17T18:17:14.938974+00:00'
[2025-06-17T18:17:15.445+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-06-17T18:17:15.462+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-06-17T18:17:15.464+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'set -o pipefail && spark-submit --master spark://spark-master:7077 --deploy-mode client /opt/***/code/stage.py --process-date 2025-06-17 2>&1']
[2025-06-17T18:17:15.474+0000] {subprocess.py:99} INFO - Output:
[2025-06-17T18:17:18.271+0000] {subprocess.py:106} INFO - 25/06/17 18:17:18 INFO SparkContext: Running Spark version 3.3.4
[2025-06-17T18:17:18.320+0000] {subprocess.py:106} INFO - 25/06/17 18:17:18 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-06-17T18:17:18.400+0000] {subprocess.py:106} INFO - 25/06/17 18:17:18 INFO ResourceUtils: ==============================================================
[2025-06-17T18:17:18.401+0000] {subprocess.py:106} INFO - 25/06/17 18:17:18 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-06-17T18:17:18.402+0000] {subprocess.py:106} INFO - 25/06/17 18:17:18 INFO ResourceUtils: ==============================================================
[2025-06-17T18:17:18.402+0000] {subprocess.py:106} INFO - 25/06/17 18:17:18 INFO SparkContext: Submitted application: CSV to Hive Tables - staging
[2025-06-17T18:17:18.421+0000] {subprocess.py:106} INFO - 25/06/17 18:17:18 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-06-17T18:17:18.429+0000] {subprocess.py:106} INFO - 25/06/17 18:17:18 INFO ResourceProfile: Limiting resource is cpu
[2025-06-17T18:17:18.430+0000] {subprocess.py:106} INFO - 25/06/17 18:17:18 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-06-17T18:17:18.472+0000] {subprocess.py:106} INFO - 25/06/17 18:17:18 INFO SecurityManager: Changing view acls to: ***
[2025-06-17T18:17:18.473+0000] {subprocess.py:106} INFO - 25/06/17 18:17:18 INFO SecurityManager: Changing modify acls to: ***
[2025-06-17T18:17:18.473+0000] {subprocess.py:106} INFO - 25/06/17 18:17:18 INFO SecurityManager: Changing view acls groups to:
[2025-06-17T18:17:18.474+0000] {subprocess.py:106} INFO - 25/06/17 18:17:18 INFO SecurityManager: Changing modify acls groups to:
[2025-06-17T18:17:18.474+0000] {subprocess.py:106} INFO - 25/06/17 18:17:18 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(***); groups with view permissions: Set(); users  with modify permissions: Set(***); groups with modify permissions: Set()
[2025-06-17T18:17:18.691+0000] {subprocess.py:106} INFO - 25/06/17 18:17:18 INFO Utils: Successfully started service 'sparkDriver' on port 45169.
[2025-06-17T18:17:18.739+0000] {subprocess.py:106} INFO - 25/06/17 18:17:18 INFO SparkEnv: Registering MapOutputTracker
[2025-06-17T18:17:18.775+0000] {subprocess.py:106} INFO - 25/06/17 18:17:18 INFO SparkEnv: Registering BlockManagerMaster
[2025-06-17T18:17:18.793+0000] {subprocess.py:106} INFO - 25/06/17 18:17:18 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-06-17T18:17:18.794+0000] {subprocess.py:106} INFO - 25/06/17 18:17:18 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-06-17T18:17:18.797+0000] {subprocess.py:106} INFO - 25/06/17 18:17:18 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-06-17T18:17:18.819+0000] {subprocess.py:106} INFO - 25/06/17 18:17:18 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-f2a82580-da1e-48f7-9d44-797653e6eec5
[2025-06-17T18:17:18.838+0000] {subprocess.py:106} INFO - 25/06/17 18:17:18 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-06-17T18:17:18.858+0000] {subprocess.py:106} INFO - 25/06/17 18:17:18 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-06-17T18:17:19.053+0000] {subprocess.py:106} INFO - 25/06/17 18:17:19 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-06-17T18:17:19.161+0000] {subprocess.py:106} INFO - 25/06/17 18:17:19 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
[2025-06-17T18:17:19.215+0000] {subprocess.py:106} INFO - 25/06/17 18:17:19 INFO TransportClientFactory: Successfully created connection to spark-master/172.28.0.4:7077 after 32 ms (0 ms spent in bootstraps)
[2025-06-17T18:17:19.993+0000] {subprocess.py:106} INFO - 25/06/17 18:17:19 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20250617181719-0000
[2025-06-17T18:17:19.999+0000] {subprocess.py:106} INFO - 25/06/17 18:17:19 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 34667.
[2025-06-17T18:17:20.000+0000] {subprocess.py:106} INFO - 25/06/17 18:17:19 INFO NettyBlockTransferService: Server created on b11ca03b7444:34667
[2025-06-17T18:17:20.001+0000] {subprocess.py:106} INFO - 25/06/17 18:17:20 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-06-17T18:17:20.007+0000] {subprocess.py:106} INFO - 25/06/17 18:17:20 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, b11ca03b7444, 34667, None)
[2025-06-17T18:17:20.010+0000] {subprocess.py:106} INFO - 25/06/17 18:17:20 INFO BlockManagerMasterEndpoint: Registering block manager b11ca03b7444:34667 with 434.4 MiB RAM, BlockManagerId(driver, b11ca03b7444, 34667, None)
[2025-06-17T18:17:20.012+0000] {subprocess.py:106} INFO - 25/06/17 18:17:20 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, b11ca03b7444, 34667, None)
[2025-06-17T18:17:20.013+0000] {subprocess.py:106} INFO - 25/06/17 18:17:20 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, b11ca03b7444, 34667, None)
[2025-06-17T18:17:20.092+0000] {subprocess.py:106} INFO - 25/06/17 18:17:20 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20250617181719-0000/0 on worker-20250617131755-172.28.0.9-39229 (172.28.0.9:39229) with 6 core(s)
[2025-06-17T18:17:20.095+0000] {subprocess.py:106} INFO - 25/06/17 18:17:20 INFO StandaloneSchedulerBackend: Granted executor ID app-20250617181719-0000/0 on hostPort 172.28.0.9:39229 with 6 core(s), 1024.0 MiB RAM
[2025-06-17T18:17:20.182+0000] {subprocess.py:106} INFO - 25/06/17 18:17:20 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2025-06-17T18:17:20.365+0000] {subprocess.py:106} INFO - 25/06/17 18:17:20 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-06-17T18:17:20.374+0000] {subprocess.py:106} INFO - 25/06/17 18:17:20 INFO SharedState: Warehouse path is 'file:/tmp/***tmpwqm6r20j/spark-warehouse'.
[2025-06-17T18:17:20.688+0000] {subprocess.py:106} INFO - 25/06/17 18:17:20 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20250617181719-0000/0 is now RUNNING
[2025-06-17T18:17:20.868+0000] {subprocess.py:106} INFO - 25/06/17 18:17:20 WARN SparkSession: Using an existing Spark session; only runtime SQL configurations will take effect.
[2025-06-17T18:17:22.648+0000] {subprocess.py:106} INFO - 25/06/17 18:17:22 INFO HiveConf: Found configuration file null
[2025-06-17T18:17:22.661+0000] {subprocess.py:106} INFO - 25/06/17 18:17:22 INFO HiveUtils: Initializing HiveMetastoreConnection version 2.3.9 using Spark classes.
[2025-06-17T18:17:22.860+0000] {subprocess.py:106} INFO - 25/06/17 18:17:22 INFO HiveClientImpl: Warehouse location for Hive client (version 2.3.9) is file:/tmp/***tmpwqm6r20j/spark-warehouse
[2025-06-17T18:17:22.981+0000] {subprocess.py:106} INFO - 25/06/17 18:17:22 WARN HiveConf: HiveConf of name hive.stats.jdbc.timeout does not exist
[2025-06-17T18:17:22.981+0000] {subprocess.py:106} INFO - 25/06/17 18:17:22 WARN HiveConf: HiveConf of name hive.stats.retries.wait does not exist
[2025-06-17T18:17:22.982+0000] {subprocess.py:106} INFO - 25/06/17 18:17:22 INFO HiveMetaStore: 0: Opening raw store with implementation class:org.apache.hadoop.hive.metastore.ObjectStore
[2025-06-17T18:17:23.015+0000] {subprocess.py:106} INFO - 25/06/17 18:17:23 INFO ObjectStore: ObjectStore, initialize called
[2025-06-17T18:17:23.153+0000] {subprocess.py:106} INFO - 25/06/17 18:17:23 INFO Persistence: Property hive.metastore.integral.jdo.pushdown unknown - will be ignored
[2025-06-17T18:17:23.154+0000] {subprocess.py:106} INFO - 25/06/17 18:17:23 INFO Persistence: Property datanucleus.cache.level2 unknown - will be ignored
[2025-06-17T18:17:23.502+0000] {subprocess.py:106} INFO - 25/06/17 18:17:23 INFO CoarseGrainedSchedulerBackend$DriverEndpoint: Registered executor NettyRpcEndpointRef(spark-client://Executor) (172.28.0.9:47214) with ID 0,  ResourceProfileId 0
[2025-06-17T18:17:23.568+0000] {subprocess.py:106} INFO - 25/06/17 18:17:23 INFO BlockManagerMasterEndpoint: Registering block manager 172.28.0.9:43973 with 434.4 MiB RAM, BlockManagerId(0, 172.28.0.9, 43973, None)
[2025-06-17T18:17:24.378+0000] {subprocess.py:106} INFO - 25/06/17 18:17:24 INFO ObjectStore: Setting MetaStore object pin classes with hive.metastore.cache.pinobjtypes="Table,StorageDescriptor,SerDeInfo,Partition,Database,Type,FieldSchema,Order"
[2025-06-17T18:17:25.795+0000] {subprocess.py:106} INFO - 25/06/17 18:17:25 INFO MetaStoreDirectSql: Using direct SQL, underlying DB is DERBY
[2025-06-17T18:17:25.796+0000] {subprocess.py:106} INFO - 25/06/17 18:17:25 INFO ObjectStore: Initialized ObjectStore
[2025-06-17T18:17:25.856+0000] {subprocess.py:106} INFO - 25/06/17 18:17:25 WARN ObjectStore: Version information not found in metastore. hive.metastore.schema.verification is not enabled so recording the schema version 2.3.0
[2025-06-17T18:17:25.857+0000] {subprocess.py:106} INFO - 25/06/17 18:17:25 WARN ObjectStore: setMetaStoreSchemaVersion called but recording version is disabled: version = 2.3.0, comment = Set by MetaStore UNKNOWN@172.28.0.18
[2025-06-17T18:17:25.876+0000] {subprocess.py:106} INFO - 25/06/17 18:17:25 WARN ObjectStore: Failed to get database default, returning NoSuchObjectException
[2025-06-17T18:17:26.056+0000] {subprocess.py:106} INFO - 25/06/17 18:17:26 INFO HiveMetaStore: Added admin role in metastore
[2025-06-17T18:17:26.060+0000] {subprocess.py:106} INFO - 25/06/17 18:17:26 INFO HiveMetaStore: Added public role in metastore
[2025-06-17T18:17:26.122+0000] {subprocess.py:106} INFO - 25/06/17 18:17:26 INFO HiveMetaStore: No user is added in admin role, since config is empty
[2025-06-17T18:17:26.216+0000] {subprocess.py:106} INFO - 25/06/17 18:17:26 INFO HiveMetaStore: 0: get_database: default
[2025-06-17T18:17:26.218+0000] {subprocess.py:106} INFO - 25/06/17 18:17:26 INFO audit: ugi=***	ip=unknown-ip-addr	cmd=get_database: default
[2025-06-17T18:17:26.231+0000] {subprocess.py:106} INFO - 25/06/17 18:17:26 INFO HiveMetaStore: 0: get_database: staging
[2025-06-17T18:17:26.232+0000] {subprocess.py:106} INFO - 25/06/17 18:17:26 INFO audit: ugi=***	ip=unknown-ip-addr	cmd=get_database: staging
[2025-06-17T18:17:26.232+0000] {subprocess.py:106} INFO - 25/06/17 18:17:26 WARN ObjectStore: Failed to get database staging, returning NoSuchObjectException
[2025-06-17T18:17:26.233+0000] {subprocess.py:106} INFO - 25/06/17 18:17:26 INFO HiveMetaStore: 0: get_database: staging
[2025-06-17T18:17:26.234+0000] {subprocess.py:106} INFO - 25/06/17 18:17:26 INFO audit: ugi=***	ip=unknown-ip-addr	cmd=get_database: staging
[2025-06-17T18:17:26.235+0000] {subprocess.py:106} INFO - 25/06/17 18:17:26 WARN ObjectStore: Failed to get database staging, returning NoSuchObjectException
[2025-06-17T18:17:26.247+0000] {subprocess.py:106} INFO - 25/06/17 18:17:26 INFO HiveMetaStore: 0: get_database: global_temp
[2025-06-17T18:17:26.248+0000] {subprocess.py:106} INFO - 25/06/17 18:17:26 INFO audit: ugi=***	ip=unknown-ip-addr	cmd=get_database: global_temp
[2025-06-17T18:17:26.249+0000] {subprocess.py:106} INFO - 25/06/17 18:17:26 WARN ObjectStore: Failed to get database global_temp, returning NoSuchObjectException
[2025-06-17T18:17:26.253+0000] {subprocess.py:106} INFO - 25/06/17 18:17:26 INFO HiveMetaStore: 0: create_database: Database(name:staging, description:, locationUri:file:/tmp/***tmpwqm6r20j/spark-warehouse/staging.db, parameters:{}, ownerName:***)
[2025-06-17T18:17:26.254+0000] {subprocess.py:106} INFO - 25/06/17 18:17:26 INFO audit: ugi=***	ip=unknown-ip-addr	cmd=create_database: Database(name:staging, description:, locationUri:file:/tmp/***tmpwqm6r20j/spark-warehouse/staging.db, parameters:{}, ownerName:***)
[2025-06-17T18:17:26.254+0000] {subprocess.py:106} INFO - 25/06/17 18:17:26 WARN ObjectStore: Failed to get database staging, returning NoSuchObjectException
[2025-06-17T18:17:26.255+0000] {subprocess.py:106} INFO - 25/06/17 18:17:26 INFO FileUtils: Creating directory if it doesn't exist: file:/tmp/***tmpwqm6r20j/spark-warehouse/staging.db
[2025-06-17T18:17:26.386+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-06-17T18:17:26.386+0000] {subprocess.py:106} INFO -   File "/opt/***/code/stage.py", line 83, in <module>
[2025-06-17T18:17:26.388+0000] {subprocess.py:106} INFO -     main()
[2025-06-17T18:17:26.388+0000] {subprocess.py:106} INFO -   File "/opt/***/code/stage.py", line 58, in main
[2025-06-17T18:17:26.390+0000] {subprocess.py:106} INFO -     if not path_exists(spark, hdfs_path):
[2025-06-17T18:17:26.390+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-06-17T18:17:26.391+0000] {subprocess.py:106} INFO -   File "/opt/***/code/stage.py", line 10, in path_exists
[2025-06-17T18:17:26.392+0000] {subprocess.py:106} INFO -     return fs.exists(p)
[2025-06-17T18:17:26.393+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^
[2025-06-17T18:17:26.393+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/py4j-0.10.9.5-src.zip/py4j/java_gateway.py", line 1321, in __call__
[2025-06-17T18:17:26.393+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 196, in deco
[2025-06-17T18:17:26.397+0000] {subprocess.py:106} INFO - pyspark.sql.utils.IllegalArgumentException: Wrong FS: hdfs://namenode:9000/landing/item/2025-06-17.csv, expected: file:///
[2025-06-17T18:17:26.440+0000] {subprocess.py:106} INFO - 25/06/17 18:17:26 INFO SparkContext: Invoking stop() from shutdown hook
[2025-06-17T18:17:26.449+0000] {subprocess.py:106} INFO - 25/06/17 18:17:26 INFO SparkUI: Stopped Spark web UI at http://b11ca03b7444:4040
[2025-06-17T18:17:26.452+0000] {subprocess.py:106} INFO - 25/06/17 18:17:26 INFO StandaloneSchedulerBackend: Shutting down all executors
[2025-06-17T18:17:26.452+0000] {subprocess.py:106} INFO - 25/06/17 18:17:26 INFO CoarseGrainedSchedulerBackend$DriverEndpoint: Asking each executor to shut down
[2025-06-17T18:17:26.466+0000] {subprocess.py:106} INFO - 25/06/17 18:17:26 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-06-17T18:17:26.504+0000] {subprocess.py:106} INFO - 25/06/17 18:17:26 INFO MemoryStore: MemoryStore cleared
[2025-06-17T18:17:26.504+0000] {subprocess.py:106} INFO - 25/06/17 18:17:26 INFO BlockManager: BlockManager stopped
[2025-06-17T18:17:26.511+0000] {subprocess.py:106} INFO - 25/06/17 18:17:26 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-06-17T18:17:26.517+0000] {subprocess.py:106} INFO - 25/06/17 18:17:26 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-06-17T18:17:26.526+0000] {subprocess.py:106} INFO - 25/06/17 18:17:26 INFO SparkContext: Successfully stopped SparkContext
[2025-06-17T18:17:26.527+0000] {subprocess.py:106} INFO - 25/06/17 18:17:26 INFO ShutdownHookManager: Shutdown hook called
[2025-06-17T18:17:26.528+0000] {subprocess.py:106} INFO - 25/06/17 18:17:26 INFO ShutdownHookManager: Deleting directory /tmp/spark-bccab991-7141-4b1a-ab9c-9e2d6932324d
[2025-06-17T18:17:26.534+0000] {subprocess.py:106} INFO - 25/06/17 18:17:26 INFO ShutdownHookManager: Deleting directory /tmp/spark-bccab991-7141-4b1a-ab9c-9e2d6932324d/pyspark-ad333286-9639-445e-94d0-fcefed4c8d27
[2025-06-17T18:17:26.542+0000] {subprocess.py:106} INFO - 25/06/17 18:17:26 INFO ShutdownHookManager: Deleting directory /tmp/spark-67e0a03d-d976-4353-936f-8eee7deaaa27
[2025-06-17T18:17:26.585+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-06-17T18:17:26.606+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-06-17T18:17:26.613+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=ingest_csv_to_hive, task_id=spark_ingest, run_id=manual__2025-06-17T18:17:14.938974+00:00, execution_date=20250617T181714, start_date=20250617T181715, end_date=20250617T181726
[2025-06-17T18:17:26.631+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-06-17T18:17:26.632+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 14 for task spark_ingest (Bash command failed. The command returned a non-zero exit code 1.; 727)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-06-17T18:17:26.661+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-06-17T18:17:26.684+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-17T18:17:26.686+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
