[2025-06-17T18:00:07.503+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-17T18:00:07.522+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_csv_to_hive.spark_ingest scheduled__2025-06-16T00:00:00+00:00 [queued]>
[2025-06-17T18:00:07.530+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_csv_to_hive.spark_ingest scheduled__2025-06-16T00:00:00+00:00 [queued]>
[2025-06-17T18:00:07.531+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-06-17T18:00:07.544+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): spark_ingest> on 2025-06-16 00:00:00+00:00
[2025-06-17T18:00:07.552+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=205) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-17T18:00:07.552+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ingest_csv_to_hive', 'spark_ingest', 'scheduled__2025-06-16T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/ETL_flow.py', '--cfg-path', '/tmp/tmpwanyl4c2']
[2025-06-17T18:00:07.554+0000] {standard_task_runner.py:72} INFO - Started process 206 to run task
[2025-06-17T18:00:07.554+0000] {standard_task_runner.py:105} INFO - Job 11: Subtask spark_ingest
[2025-06-17T18:00:07.575+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-17T18:00:07.619+0000] {task_command.py:467} INFO - Running <TaskInstance: ingest_csv_to_hive.spark_ingest scheduled__2025-06-16T00:00:00+00:00 [running]> on host b11ca03b7444
[2025-06-17T18:00:07.621+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-17T18:00:07.718+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_csv_to_hive' AIRFLOW_CTX_TASK_ID='spark_ingest' AIRFLOW_CTX_EXECUTION_DATE='2025-06-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-16T00:00:00+00:00'
[2025-06-17T18:00:07.719+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-06-17T18:00:07.756+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-06-17T18:00:07.757+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'set -o pipefail && spark-submit /opt/***/code/stage.py --process-date 2025-06-16 2>&1']
[2025-06-17T18:00:07.766+0000] {subprocess.py:99} INFO - Output:
[2025-06-17T18:00:10.407+0000] {subprocess.py:106} INFO - 25/06/17 18:00:10 INFO SparkContext: Running Spark version 3.3.4
[2025-06-17T18:00:10.453+0000] {subprocess.py:106} INFO - 25/06/17 18:00:10 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-06-17T18:00:10.533+0000] {subprocess.py:106} INFO - 25/06/17 18:00:10 INFO ResourceUtils: ==============================================================
[2025-06-17T18:00:10.534+0000] {subprocess.py:106} INFO - 25/06/17 18:00:10 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-06-17T18:00:10.535+0000] {subprocess.py:106} INFO - 25/06/17 18:00:10 INFO ResourceUtils: ==============================================================
[2025-06-17T18:00:10.536+0000] {subprocess.py:106} INFO - 25/06/17 18:00:10 INFO SparkContext: Submitted application: CSV to Hive Tables - staging
[2025-06-17T18:00:10.556+0000] {subprocess.py:106} INFO - 25/06/17 18:00:10 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-06-17T18:00:10.568+0000] {subprocess.py:106} INFO - 25/06/17 18:00:10 INFO ResourceProfile: Limiting resource is cpu
[2025-06-17T18:00:10.568+0000] {subprocess.py:106} INFO - 25/06/17 18:00:10 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-06-17T18:00:10.614+0000] {subprocess.py:106} INFO - 25/06/17 18:00:10 INFO SecurityManager: Changing view acls to: ***
[2025-06-17T18:00:10.615+0000] {subprocess.py:106} INFO - 25/06/17 18:00:10 INFO SecurityManager: Changing modify acls to: ***
[2025-06-17T18:00:10.616+0000] {subprocess.py:106} INFO - 25/06/17 18:00:10 INFO SecurityManager: Changing view acls groups to:
[2025-06-17T18:00:10.617+0000] {subprocess.py:106} INFO - 25/06/17 18:00:10 INFO SecurityManager: Changing modify acls groups to:
[2025-06-17T18:00:10.617+0000] {subprocess.py:106} INFO - 25/06/17 18:00:10 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(***); groups with view permissions: Set(); users  with modify permissions: Set(***); groups with modify permissions: Set()
[2025-06-17T18:00:10.963+0000] {subprocess.py:106} INFO - 25/06/17 18:00:10 INFO Utils: Successfully started service 'sparkDriver' on port 42255.
[2025-06-17T18:00:11.000+0000] {subprocess.py:106} INFO - 25/06/17 18:00:11 INFO SparkEnv: Registering MapOutputTracker
[2025-06-17T18:00:11.056+0000] {subprocess.py:106} INFO - 25/06/17 18:00:11 INFO SparkEnv: Registering BlockManagerMaster
[2025-06-17T18:00:11.078+0000] {subprocess.py:106} INFO - 25/06/17 18:00:11 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-06-17T18:00:11.080+0000] {subprocess.py:106} INFO - 25/06/17 18:00:11 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-06-17T18:00:11.086+0000] {subprocess.py:106} INFO - 25/06/17 18:00:11 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-06-17T18:00:11.112+0000] {subprocess.py:106} INFO - 25/06/17 18:00:11 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-7f66fe65-4a83-4573-8831-a546e0bf6093
[2025-06-17T18:00:11.134+0000] {subprocess.py:106} INFO - 25/06/17 18:00:11 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-06-17T18:00:11.155+0000] {subprocess.py:106} INFO - 25/06/17 18:00:11 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-06-17T18:00:11.377+0000] {subprocess.py:106} INFO - 25/06/17 18:00:11 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-06-17T18:00:11.482+0000] {subprocess.py:106} INFO - 25/06/17 18:00:11 INFO Executor: Starting executor ID driver on host b11ca03b7444
[2025-06-17T18:00:11.493+0000] {subprocess.py:106} INFO - 25/06/17 18:00:11 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2025-06-17T18:00:11.516+0000] {subprocess.py:106} INFO - 25/06/17 18:00:11 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 36075.
[2025-06-17T18:00:11.517+0000] {subprocess.py:106} INFO - 25/06/17 18:00:11 INFO NettyBlockTransferService: Server created on b11ca03b7444:36075
[2025-06-17T18:00:11.519+0000] {subprocess.py:106} INFO - 25/06/17 18:00:11 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-06-17T18:00:11.525+0000] {subprocess.py:106} INFO - 25/06/17 18:00:11 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, b11ca03b7444, 36075, None)
[2025-06-17T18:00:11.530+0000] {subprocess.py:106} INFO - 25/06/17 18:00:11 INFO BlockManagerMasterEndpoint: Registering block manager b11ca03b7444:36075 with 434.4 MiB RAM, BlockManagerId(driver, b11ca03b7444, 36075, None)
[2025-06-17T18:00:11.532+0000] {subprocess.py:106} INFO - 25/06/17 18:00:11 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, b11ca03b7444, 36075, None)
[2025-06-17T18:00:11.534+0000] {subprocess.py:106} INFO - 25/06/17 18:00:11 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, b11ca03b7444, 36075, None)
[2025-06-17T18:00:11.968+0000] {subprocess.py:106} INFO - 25/06/17 18:00:11 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-06-17T18:00:11.976+0000] {subprocess.py:106} INFO - 25/06/17 18:00:11 INFO SharedState: Warehouse path is 'file:/tmp/***tmpo832mnm5/spark-warehouse'.
[2025-06-17T18:00:12.555+0000] {subprocess.py:106} INFO - 25/06/17 18:00:12 WARN SparkSession: Using an existing Spark session; only runtime SQL configurations will take effect.
[2025-06-17T18:00:14.156+0000] {subprocess.py:106} INFO - 25/06/17 18:00:14 INFO HiveConf: Found configuration file null
[2025-06-17T18:00:14.164+0000] {subprocess.py:106} INFO - 25/06/17 18:00:14 INFO HiveUtils: Initializing HiveMetastoreConnection version 2.3.9 using Spark classes.
[2025-06-17T18:00:14.357+0000] {subprocess.py:106} INFO - 25/06/17 18:00:14 INFO HiveClientImpl: Warehouse location for Hive client (version 2.3.9) is file:/tmp/***tmpo832mnm5/spark-warehouse
[2025-06-17T18:00:14.467+0000] {subprocess.py:106} INFO - 25/06/17 18:00:14 WARN HiveConf: HiveConf of name hive.stats.jdbc.timeout does not exist
[2025-06-17T18:00:14.468+0000] {subprocess.py:106} INFO - 25/06/17 18:00:14 WARN HiveConf: HiveConf of name hive.stats.retries.wait does not exist
[2025-06-17T18:00:14.469+0000] {subprocess.py:106} INFO - 25/06/17 18:00:14 INFO HiveMetaStore: 0: Opening raw store with implementation class:org.apache.hadoop.hive.metastore.ObjectStore
[2025-06-17T18:00:14.503+0000] {subprocess.py:106} INFO - 25/06/17 18:00:14 INFO ObjectStore: ObjectStore, initialize called
[2025-06-17T18:00:14.619+0000] {subprocess.py:106} INFO - 25/06/17 18:00:14 INFO Persistence: Property hive.metastore.integral.jdo.pushdown unknown - will be ignored
[2025-06-17T18:00:14.619+0000] {subprocess.py:106} INFO - 25/06/17 18:00:14 INFO Persistence: Property datanucleus.cache.level2 unknown - will be ignored
[2025-06-17T18:00:15.855+0000] {subprocess.py:106} INFO - 25/06/17 18:00:15 INFO ObjectStore: Setting MetaStore object pin classes with hive.metastore.cache.pinobjtypes="Table,StorageDescriptor,SerDeInfo,Partition,Database,Type,FieldSchema,Order"
[2025-06-17T18:00:17.528+0000] {subprocess.py:106} INFO - 25/06/17 18:00:17 INFO MetaStoreDirectSql: Using direct SQL, underlying DB is DERBY
[2025-06-17T18:00:17.530+0000] {subprocess.py:106} INFO - 25/06/17 18:00:17 INFO ObjectStore: Initialized ObjectStore
[2025-06-17T18:00:17.594+0000] {subprocess.py:106} INFO - 25/06/17 18:00:17 WARN ObjectStore: Version information not found in metastore. hive.metastore.schema.verification is not enabled so recording the schema version 2.3.0
[2025-06-17T18:00:17.594+0000] {subprocess.py:106} INFO - 25/06/17 18:00:17 WARN ObjectStore: setMetaStoreSchemaVersion called but recording version is disabled: version = 2.3.0, comment = Set by MetaStore UNKNOWN@172.28.0.18
[2025-06-17T18:00:17.611+0000] {subprocess.py:106} INFO - 25/06/17 18:00:17 WARN ObjectStore: Failed to get database default, returning NoSuchObjectException
[2025-06-17T18:00:17.772+0000] {subprocess.py:106} INFO - 25/06/17 18:00:17 INFO HiveMetaStore: Added admin role in metastore
[2025-06-17T18:00:17.776+0000] {subprocess.py:106} INFO - 25/06/17 18:00:17 INFO HiveMetaStore: Added public role in metastore
[2025-06-17T18:00:17.853+0000] {subprocess.py:106} INFO - 25/06/17 18:00:17 INFO HiveMetaStore: No user is added in admin role, since config is empty
[2025-06-17T18:00:17.945+0000] {subprocess.py:106} INFO - 25/06/17 18:00:17 INFO HiveMetaStore: 0: get_database: default
[2025-06-17T18:00:17.946+0000] {subprocess.py:106} INFO - 25/06/17 18:00:17 INFO audit: ugi=***	ip=unknown-ip-addr	cmd=get_database: default
[2025-06-17T18:00:17.965+0000] {subprocess.py:106} INFO - 25/06/17 18:00:17 INFO HiveMetaStore: 0: get_database: staging
[2025-06-17T18:00:17.967+0000] {subprocess.py:106} INFO - 25/06/17 18:00:17 INFO audit: ugi=***	ip=unknown-ip-addr	cmd=get_database: staging
[2025-06-17T18:00:17.968+0000] {subprocess.py:106} INFO - 25/06/17 18:00:17 WARN ObjectStore: Failed to get database staging, returning NoSuchObjectException
[2025-06-17T18:00:17.970+0000] {subprocess.py:106} INFO - 25/06/17 18:00:17 INFO HiveMetaStore: 0: get_database: staging
[2025-06-17T18:00:17.971+0000] {subprocess.py:106} INFO - 25/06/17 18:00:17 INFO audit: ugi=***	ip=unknown-ip-addr	cmd=get_database: staging
[2025-06-17T18:00:17.971+0000] {subprocess.py:106} INFO - 25/06/17 18:00:17 WARN ObjectStore: Failed to get database staging, returning NoSuchObjectException
[2025-06-17T18:00:17.986+0000] {subprocess.py:106} INFO - 25/06/17 18:00:17 INFO HiveMetaStore: 0: get_database: global_temp
[2025-06-17T18:00:17.987+0000] {subprocess.py:106} INFO - 25/06/17 18:00:17 INFO audit: ugi=***	ip=unknown-ip-addr	cmd=get_database: global_temp
[2025-06-17T18:00:17.988+0000] {subprocess.py:106} INFO - 25/06/17 18:00:17 WARN ObjectStore: Failed to get database global_temp, returning NoSuchObjectException
[2025-06-17T18:00:17.994+0000] {subprocess.py:106} INFO - 25/06/17 18:00:17 INFO HiveMetaStore: 0: create_database: Database(name:staging, description:, locationUri:file:/tmp/***tmpo832mnm5/spark-warehouse/staging.db, parameters:{}, ownerName:***)
[2025-06-17T18:00:17.994+0000] {subprocess.py:106} INFO - 25/06/17 18:00:17 INFO audit: ugi=***	ip=unknown-ip-addr	cmd=create_database: Database(name:staging, description:, locationUri:file:/tmp/***tmpo832mnm5/spark-warehouse/staging.db, parameters:{}, ownerName:***)
[2025-06-17T18:00:17.995+0000] {subprocess.py:106} INFO - 25/06/17 18:00:17 WARN ObjectStore: Failed to get database staging, returning NoSuchObjectException
[2025-06-17T18:00:17.996+0000] {subprocess.py:106} INFO - 25/06/17 18:00:17 INFO FileUtils: Creating directory if it doesn't exist: file:/tmp/***tmpo832mnm5/spark-warehouse/staging.db
[2025-06-17T18:00:18.161+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-06-17T18:00:18.162+0000] {subprocess.py:106} INFO -   File "/opt/***/code/stage.py", line 83, in <module>
[2025-06-17T18:00:18.165+0000] {subprocess.py:106} INFO -     main()
[2025-06-17T18:00:18.166+0000] {subprocess.py:106} INFO -   File "/opt/***/code/stage.py", line 58, in main
[2025-06-17T18:00:18.168+0000] {subprocess.py:106} INFO -     if not path_exists(spark, hdfs_path):
[2025-06-17T18:00:18.168+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-06-17T18:00:18.169+0000] {subprocess.py:106} INFO -   File "/opt/***/code/stage.py", line 10, in path_exists
[2025-06-17T18:00:18.170+0000] {subprocess.py:106} INFO -     return fs.exists(p)
[2025-06-17T18:00:18.171+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^
[2025-06-17T18:00:18.171+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/py4j-0.10.9.5-src.zip/py4j/java_gateway.py", line 1321, in __call__
[2025-06-17T18:00:18.172+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 196, in deco
[2025-06-17T18:00:18.177+0000] {subprocess.py:106} INFO - pyspark.sql.utils.IllegalArgumentException: Wrong FS: hdfs://namenode:9000/landing/item/2025-06-16.csv, expected: file:///
[2025-06-17T18:00:18.232+0000] {subprocess.py:106} INFO - 25/06/17 18:00:18 INFO SparkContext: Invoking stop() from shutdown hook
[2025-06-17T18:00:18.244+0000] {subprocess.py:106} INFO - 25/06/17 18:00:18 INFO SparkUI: Stopped Spark web UI at http://b11ca03b7444:4040
[2025-06-17T18:00:18.255+0000] {subprocess.py:106} INFO - 25/06/17 18:00:18 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-06-17T18:00:18.268+0000] {subprocess.py:106} INFO - 25/06/17 18:00:18 INFO MemoryStore: MemoryStore cleared
[2025-06-17T18:00:18.269+0000] {subprocess.py:106} INFO - 25/06/17 18:00:18 INFO BlockManager: BlockManager stopped
[2025-06-17T18:00:18.275+0000] {subprocess.py:106} INFO - 25/06/17 18:00:18 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-06-17T18:00:18.279+0000] {subprocess.py:106} INFO - 25/06/17 18:00:18 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-06-17T18:00:18.295+0000] {subprocess.py:106} INFO - 25/06/17 18:00:18 INFO SparkContext: Successfully stopped SparkContext
[2025-06-17T18:00:18.296+0000] {subprocess.py:106} INFO - 25/06/17 18:00:18 INFO ShutdownHookManager: Shutdown hook called
[2025-06-17T18:00:18.297+0000] {subprocess.py:106} INFO - 25/06/17 18:00:18 INFO ShutdownHookManager: Deleting directory /tmp/spark-39771542-9d36-4fd5-9599-bf724d74ecca
[2025-06-17T18:00:18.301+0000] {subprocess.py:106} INFO - 25/06/17 18:00:18 INFO ShutdownHookManager: Deleting directory /tmp/spark-546d8be0-3184-4146-bf35-d2ef944413e4
[2025-06-17T18:00:18.304+0000] {subprocess.py:106} INFO - 25/06/17 18:00:18 INFO ShutdownHookManager: Deleting directory /tmp/spark-39771542-9d36-4fd5-9599-bf724d74ecca/pyspark-1bb10666-8e43-4a68-847e-7a21474a7faf
[2025-06-17T18:00:18.347+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-06-17T18:00:18.369+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-06-17T18:00:18.374+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=ingest_csv_to_hive, task_id=spark_ingest, run_id=scheduled__2025-06-16T00:00:00+00:00, execution_date=20250616T000000, start_date=20250617T180007, end_date=20250617T180018
[2025-06-17T18:00:18.388+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-06-17T18:00:18.389+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 11 for task spark_ingest (Bash command failed. The command returned a non-zero exit code 1.; 206)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-06-17T18:00:18.430+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-06-17T18:00:18.447+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-17T18:00:18.448+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
