[2025-06-18T07:01:51.176+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-18T07:01:51.196+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_csv_to_hive.spark_ingest scheduled__2025-06-17T00:00:00+00:00 [queued]>
[2025-06-18T07:01:51.204+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_csv_to_hive.spark_ingest scheduled__2025-06-17T00:00:00+00:00 [queued]>
[2025-06-18T07:01:51.204+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-06-18T07:01:51.216+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): spark_ingest> on 2025-06-17 00:00:00+00:00
[2025-06-18T07:01:51.223+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=429) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-18T07:01:51.224+0000] {standard_task_runner.py:72} INFO - Started process 430 to run task
[2025-06-18T07:01:51.223+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ingest_csv_to_hive', 'spark_ingest', 'scheduled__2025-06-17T00:00:00+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/ETL_flow.py', '--cfg-path', '/tmp/tmpqnjqlijt']
[2025-06-18T07:01:51.225+0000] {standard_task_runner.py:105} INFO - Job 52: Subtask spark_ingest
[2025-06-18T07:01:51.242+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-18T07:01:51.282+0000] {task_command.py:467} INFO - Running <TaskInstance: ingest_csv_to_hive.spark_ingest scheduled__2025-06-17T00:00:00+00:00 [running]> on host b11ca03b7444
[2025-06-18T07:01:51.283+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-18T07:01:51.370+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_csv_to_hive' AIRFLOW_CTX_TASK_ID='spark_ingest' AIRFLOW_CTX_EXECUTION_DATE='2025-06-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-17T00:00:00+00:00'
[2025-06-18T07:01:51.371+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-06-18T07:01:51.386+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-06-18T07:01:51.387+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'set -o pipefail && spark-submit --master spark://spark-master:7077 --deploy-mode client /opt/***/code/stage.py --process-date 2025-06-17 2>&1']
[2025-06-18T07:01:51.395+0000] {subprocess.py:99} INFO - Output:
[2025-06-18T07:01:54.324+0000] {subprocess.py:106} INFO - 25/06/18 07:01:54 INFO SparkContext: Running Spark version 3.3.4
[2025-06-18T07:01:54.371+0000] {subprocess.py:106} INFO - 25/06/18 07:01:54 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-06-18T07:01:54.446+0000] {subprocess.py:106} INFO - 25/06/18 07:01:54 INFO ResourceUtils: ==============================================================
[2025-06-18T07:01:54.447+0000] {subprocess.py:106} INFO - 25/06/18 07:01:54 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-06-18T07:01:54.448+0000] {subprocess.py:106} INFO - 25/06/18 07:01:54 INFO ResourceUtils: ==============================================================
[2025-06-18T07:01:54.449+0000] {subprocess.py:106} INFO - 25/06/18 07:01:54 INFO SparkContext: Submitted application: CSV to Hive Tables - staging
[2025-06-18T07:01:54.467+0000] {subprocess.py:106} INFO - 25/06/18 07:01:54 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-06-18T07:01:54.477+0000] {subprocess.py:106} INFO - 25/06/18 07:01:54 INFO ResourceProfile: Limiting resource is cpu
[2025-06-18T07:01:54.478+0000] {subprocess.py:106} INFO - 25/06/18 07:01:54 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-06-18T07:01:54.516+0000] {subprocess.py:106} INFO - 25/06/18 07:01:54 INFO SecurityManager: Changing view acls to: ***
[2025-06-18T07:01:54.517+0000] {subprocess.py:106} INFO - 25/06/18 07:01:54 INFO SecurityManager: Changing modify acls to: ***
[2025-06-18T07:01:54.517+0000] {subprocess.py:106} INFO - 25/06/18 07:01:54 INFO SecurityManager: Changing view acls groups to:
[2025-06-18T07:01:54.518+0000] {subprocess.py:106} INFO - 25/06/18 07:01:54 INFO SecurityManager: Changing modify acls groups to:
[2025-06-18T07:01:54.518+0000] {subprocess.py:106} INFO - 25/06/18 07:01:54 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(***); groups with view permissions: Set(); users  with modify permissions: Set(***); groups with modify permissions: Set()
[2025-06-18T07:01:54.714+0000] {subprocess.py:106} INFO - 25/06/18 07:01:54 INFO Utils: Successfully started service 'sparkDriver' on port 42897.
[2025-06-18T07:01:54.739+0000] {subprocess.py:106} INFO - 25/06/18 07:01:54 INFO SparkEnv: Registering MapOutputTracker
[2025-06-18T07:01:54.773+0000] {subprocess.py:106} INFO - 25/06/18 07:01:54 INFO SparkEnv: Registering BlockManagerMaster
[2025-06-18T07:01:54.797+0000] {subprocess.py:106} INFO - 25/06/18 07:01:54 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-06-18T07:01:54.798+0000] {subprocess.py:106} INFO - 25/06/18 07:01:54 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-06-18T07:01:54.802+0000] {subprocess.py:106} INFO - 25/06/18 07:01:54 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-06-18T07:01:54.826+0000] {subprocess.py:106} INFO - 25/06/18 07:01:54 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-337284c1-ff01-4d1c-9430-92832f31e65c
[2025-06-18T07:01:54.843+0000] {subprocess.py:106} INFO - 25/06/18 07:01:54 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-06-18T07:01:54.859+0000] {subprocess.py:106} INFO - 25/06/18 07:01:54 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-06-18T07:01:55.032+0000] {subprocess.py:106} INFO - 25/06/18 07:01:55 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-06-18T07:01:55.156+0000] {subprocess.py:106} INFO - 25/06/18 07:01:55 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
[2025-06-18T07:01:55.195+0000] {subprocess.py:106} INFO - 25/06/18 07:01:55 INFO TransportClientFactory: Successfully created connection to spark-master/172.28.0.11:7077 after 22 ms (0 ms spent in bootstraps)
[2025-06-18T07:01:55.267+0000] {subprocess.py:106} INFO - 25/06/18 07:01:55 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20250618070155-0001
[2025-06-18T07:01:55.270+0000] {subprocess.py:106} INFO - 25/06/18 07:01:55 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20250618070155-0001/0 on worker-20250618065604-172.28.0.2-42337 (172.28.0.2:42337) with 6 core(s)
[2025-06-18T07:01:55.271+0000] {subprocess.py:106} INFO - 25/06/18 07:01:55 INFO StandaloneSchedulerBackend: Granted executor ID app-20250618070155-0001/0 on hostPort 172.28.0.2:42337 with 6 core(s), 1024.0 MiB RAM
[2025-06-18T07:01:55.280+0000] {subprocess.py:106} INFO - 25/06/18 07:01:55 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 39647.
[2025-06-18T07:01:55.281+0000] {subprocess.py:106} INFO - 25/06/18 07:01:55 INFO NettyBlockTransferService: Server created on b11ca03b7444:39647
[2025-06-18T07:01:55.283+0000] {subprocess.py:106} INFO - 25/06/18 07:01:55 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-06-18T07:01:55.288+0000] {subprocess.py:106} INFO - 25/06/18 07:01:55 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, b11ca03b7444, 39647, None)
[2025-06-18T07:01:55.292+0000] {subprocess.py:106} INFO - 25/06/18 07:01:55 INFO BlockManagerMasterEndpoint: Registering block manager b11ca03b7444:39647 with 434.4 MiB RAM, BlockManagerId(driver, b11ca03b7444, 39647, None)
[2025-06-18T07:01:55.294+0000] {subprocess.py:106} INFO - 25/06/18 07:01:55 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, b11ca03b7444, 39647, None)
[2025-06-18T07:01:55.295+0000] {subprocess.py:106} INFO - 25/06/18 07:01:55 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, b11ca03b7444, 39647, None)
[2025-06-18T07:01:55.322+0000] {subprocess.py:106} INFO - 25/06/18 07:01:55 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20250618070155-0001/0 is now RUNNING
[2025-06-18T07:01:55.491+0000] {subprocess.py:106} INFO - 25/06/18 07:01:55 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2025-06-18T07:01:55.785+0000] {subprocess.py:106} INFO - 25/06/18 07:01:55 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-06-18T07:01:55.796+0000] {subprocess.py:106} INFO - 25/06/18 07:01:55 INFO SharedState: Warehouse path is 'file:/tmp/***tmp7vcf1b_f/spark-warehouse'.
[2025-06-18T07:01:56.388+0000] {subprocess.py:106} INFO - 25/06/18 07:01:56 WARN SparkSession: Using an existing Spark session; only runtime SQL configurations will take effect.
[2025-06-18T07:01:58.138+0000] {subprocess.py:106} INFO - 25/06/18 07:01:58 INFO CoarseGrainedSchedulerBackend$DriverEndpoint: Registered executor NettyRpcEndpointRef(spark-client://Executor) (172.28.0.2:47506) with ID 0,  ResourceProfileId 0
[2025-06-18T07:01:58.209+0000] {subprocess.py:106} INFO - 25/06/18 07:01:58 INFO BlockManagerMasterEndpoint: Registering block manager 172.28.0.2:45985 with 434.4 MiB RAM, BlockManagerId(0, 172.28.0.2, 45985, None)
[2025-06-18T07:01:58.462+0000] {subprocess.py:106} INFO - 25/06/18 07:01:58 INFO HiveConf: Found configuration file null
[2025-06-18T07:01:58.472+0000] {subprocess.py:106} INFO - 25/06/18 07:01:58 INFO HiveUtils: Initializing HiveMetastoreConnection version 2.3.9 using Spark classes.
[2025-06-18T07:01:58.664+0000] {subprocess.py:106} INFO - 25/06/18 07:01:58 INFO HiveClientImpl: Warehouse location for Hive client (version 2.3.9) is file:/tmp/***tmp7vcf1b_f/spark-warehouse
[2025-06-18T07:01:58.771+0000] {subprocess.py:106} INFO - 25/06/18 07:01:58 WARN HiveConf: HiveConf of name hive.stats.jdbc.timeout does not exist
[2025-06-18T07:01:58.772+0000] {subprocess.py:106} INFO - 25/06/18 07:01:58 WARN HiveConf: HiveConf of name hive.stats.retries.wait does not exist
[2025-06-18T07:01:58.773+0000] {subprocess.py:106} INFO - 25/06/18 07:01:58 INFO HiveMetaStore: 0: Opening raw store with implementation class:org.apache.hadoop.hive.metastore.ObjectStore
[2025-06-18T07:01:58.798+0000] {subprocess.py:106} INFO - 25/06/18 07:01:58 INFO ObjectStore: ObjectStore, initialize called
[2025-06-18T07:01:58.905+0000] {subprocess.py:106} INFO - 25/06/18 07:01:58 INFO Persistence: Property hive.metastore.integral.jdo.pushdown unknown - will be ignored
[2025-06-18T07:01:58.906+0000] {subprocess.py:106} INFO - 25/06/18 07:01:58 INFO Persistence: Property datanucleus.cache.level2 unknown - will be ignored
[2025-06-18T07:02:00.054+0000] {subprocess.py:106} INFO - 25/06/18 07:02:00 INFO ObjectStore: Setting MetaStore object pin classes with hive.metastore.cache.pinobjtypes="Table,StorageDescriptor,SerDeInfo,Partition,Database,Type,FieldSchema,Order"
[2025-06-18T07:02:01.618+0000] {subprocess.py:106} INFO - 25/06/18 07:02:01 INFO MetaStoreDirectSql: Using direct SQL, underlying DB is DERBY
[2025-06-18T07:02:01.620+0000] {subprocess.py:106} INFO - 25/06/18 07:02:01 INFO ObjectStore: Initialized ObjectStore
[2025-06-18T07:02:01.694+0000] {subprocess.py:106} INFO - 25/06/18 07:02:01 WARN ObjectStore: Version information not found in metastore. hive.metastore.schema.verification is not enabled so recording the schema version 2.3.0
[2025-06-18T07:02:01.695+0000] {subprocess.py:106} INFO - 25/06/18 07:02:01 WARN ObjectStore: setMetaStoreSchemaVersion called but recording version is disabled: version = 2.3.0, comment = Set by MetaStore UNKNOWN@172.28.0.4
[2025-06-18T07:02:01.723+0000] {subprocess.py:106} INFO - 25/06/18 07:02:01 WARN ObjectStore: Failed to get database default, returning NoSuchObjectException
[2025-06-18T07:02:01.937+0000] {subprocess.py:106} INFO - 25/06/18 07:02:01 INFO HiveMetaStore: Added admin role in metastore
[2025-06-18T07:02:01.940+0000] {subprocess.py:106} INFO - 25/06/18 07:02:01 INFO HiveMetaStore: Added public role in metastore
[2025-06-18T07:02:02.005+0000] {subprocess.py:106} INFO - 25/06/18 07:02:02 INFO HiveMetaStore: No user is added in admin role, since config is empty
[2025-06-18T07:02:02.073+0000] {subprocess.py:106} INFO - 25/06/18 07:02:02 INFO HiveMetaStore: 0: get_database: default
[2025-06-18T07:02:02.075+0000] {subprocess.py:106} INFO - 25/06/18 07:02:02 INFO audit: ugi=***	ip=unknown-ip-addr	cmd=get_database: default
[2025-06-18T07:02:02.088+0000] {subprocess.py:106} INFO - 25/06/18 07:02:02 INFO HiveMetaStore: 0: get_database: staging
[2025-06-18T07:02:02.089+0000] {subprocess.py:106} INFO - 25/06/18 07:02:02 INFO audit: ugi=***	ip=unknown-ip-addr	cmd=get_database: staging
[2025-06-18T07:02:02.090+0000] {subprocess.py:106} INFO - 25/06/18 07:02:02 WARN ObjectStore: Failed to get database staging, returning NoSuchObjectException
[2025-06-18T07:02:02.091+0000] {subprocess.py:106} INFO - 25/06/18 07:02:02 INFO HiveMetaStore: 0: get_database: staging
[2025-06-18T07:02:02.091+0000] {subprocess.py:106} INFO - 25/06/18 07:02:02 INFO audit: ugi=***	ip=unknown-ip-addr	cmd=get_database: staging
[2025-06-18T07:02:02.092+0000] {subprocess.py:106} INFO - 25/06/18 07:02:02 WARN ObjectStore: Failed to get database staging, returning NoSuchObjectException
[2025-06-18T07:02:02.106+0000] {subprocess.py:106} INFO - 25/06/18 07:02:02 INFO HiveMetaStore: 0: get_database: global_temp
[2025-06-18T07:02:02.107+0000] {subprocess.py:106} INFO - 25/06/18 07:02:02 INFO audit: ugi=***	ip=unknown-ip-addr	cmd=get_database: global_temp
[2025-06-18T07:02:02.108+0000] {subprocess.py:106} INFO - 25/06/18 07:02:02 WARN ObjectStore: Failed to get database global_temp, returning NoSuchObjectException
[2025-06-18T07:02:02.111+0000] {subprocess.py:106} INFO - 25/06/18 07:02:02 INFO HiveMetaStore: 0: create_database: Database(name:staging, description:, locationUri:file:/tmp/***tmp7vcf1b_f/spark-warehouse/staging.db, parameters:{}, ownerName:***)
[2025-06-18T07:02:02.112+0000] {subprocess.py:106} INFO - 25/06/18 07:02:02 INFO audit: ugi=***	ip=unknown-ip-addr	cmd=create_database: Database(name:staging, description:, locationUri:file:/tmp/***tmp7vcf1b_f/spark-warehouse/staging.db, parameters:{}, ownerName:***)
[2025-06-18T07:02:02.113+0000] {subprocess.py:106} INFO - 25/06/18 07:02:02 WARN ObjectStore: Failed to get database staging, returning NoSuchObjectException
[2025-06-18T07:02:02.114+0000] {subprocess.py:106} INFO - 25/06/18 07:02:02 INFO FileUtils: Creating directory if it doesn't exist: file:/tmp/***tmp7vcf1b_f/spark-warehouse/staging.db
[2025-06-18T07:02:02.255+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-06-18T07:02:02.255+0000] {subprocess.py:106} INFO -   File "/opt/***/code/stage.py", line 84, in <module>
[2025-06-18T07:02:02.258+0000] {subprocess.py:106} INFO -     main()
[2025-06-18T07:02:02.259+0000] {subprocess.py:106} INFO -   File "/opt/***/code/stage.py", line 59, in main
[2025-06-18T07:02:02.261+0000] {subprocess.py:106} INFO -     if not path_exists(spark, hdfs_path):
[2025-06-18T07:02:02.261+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-06-18T07:02:02.262+0000] {subprocess.py:106} INFO -   File "/opt/***/code/stage.py", line 10, in path_exists
[2025-06-18T07:02:02.263+0000] {subprocess.py:106} INFO -     return fs.exists(p)
[2025-06-18T07:02:02.263+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^
[2025-06-18T07:02:02.264+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/py4j-0.10.9.5-src.zip/py4j/java_gateway.py", line 1321, in __call__
[2025-06-18T07:02:02.264+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 196, in deco
[2025-06-18T07:02:02.273+0000] {subprocess.py:106} INFO - pyspark.sql.utils.IllegalArgumentException: Wrong FS: hdfs://namenode:9000/landing/item/2025-06-17.csv, expected: file:///
[2025-06-18T07:02:02.319+0000] {subprocess.py:106} INFO - 25/06/18 07:02:02 INFO SparkContext: Invoking stop() from shutdown hook
[2025-06-18T07:02:02.329+0000] {subprocess.py:106} INFO - 25/06/18 07:02:02 INFO SparkUI: Stopped Spark web UI at http://b11ca03b7444:4040
[2025-06-18T07:02:02.332+0000] {subprocess.py:106} INFO - 25/06/18 07:02:02 INFO StandaloneSchedulerBackend: Shutting down all executors
[2025-06-18T07:02:02.333+0000] {subprocess.py:106} INFO - 25/06/18 07:02:02 INFO CoarseGrainedSchedulerBackend$DriverEndpoint: Asking each executor to shut down
[2025-06-18T07:02:02.352+0000] {subprocess.py:106} INFO - 25/06/18 07:02:02 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-06-18T07:02:02.367+0000] {subprocess.py:106} INFO - 25/06/18 07:02:02 INFO MemoryStore: MemoryStore cleared
[2025-06-18T07:02:02.369+0000] {subprocess.py:106} INFO - 25/06/18 07:02:02 INFO BlockManager: BlockManager stopped
[2025-06-18T07:02:02.379+0000] {subprocess.py:106} INFO - 25/06/18 07:02:02 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-06-18T07:02:02.382+0000] {subprocess.py:106} INFO - 25/06/18 07:02:02 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-06-18T07:02:02.396+0000] {subprocess.py:106} INFO - 25/06/18 07:02:02 INFO SparkContext: Successfully stopped SparkContext
[2025-06-18T07:02:02.397+0000] {subprocess.py:106} INFO - 25/06/18 07:02:02 INFO ShutdownHookManager: Shutdown hook called
[2025-06-18T07:02:02.397+0000] {subprocess.py:106} INFO - 25/06/18 07:02:02 INFO ShutdownHookManager: Deleting directory /tmp/spark-a55a11b7-7167-4c96-b094-8cc2c147057a
[2025-06-18T07:02:02.401+0000] {subprocess.py:106} INFO - 25/06/18 07:02:02 INFO ShutdownHookManager: Deleting directory /tmp/spark-73323c9d-395a-499e-9f8a-dc1326967c38
[2025-06-18T07:02:02.406+0000] {subprocess.py:106} INFO - 25/06/18 07:02:02 INFO ShutdownHookManager: Deleting directory /tmp/spark-a55a11b7-7167-4c96-b094-8cc2c147057a/pyspark-474922a3-48fd-4eaf-9392-1314dbd9cbbb
[2025-06-18T07:02:02.453+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-06-18T07:02:02.480+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-06-18T07:02:02.485+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=ingest_csv_to_hive, task_id=spark_ingest, run_id=scheduled__2025-06-17T00:00:00+00:00, execution_date=20250617T000000, start_date=20250618T070151, end_date=20250618T070202
[2025-06-18T07:02:02.497+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-06-18T07:02:02.498+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 52 for task spark_ingest (Bash command failed. The command returned a non-zero exit code 1.; 430)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-06-18T07:02:02.514+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-06-18T07:02:02.532+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-18T07:02:02.534+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
