[2025-06-17T18:27:49.628+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-17T18:27:49.648+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_csv_to_hive.spark_ingest manual__2025-06-17T18:22:36.742697+00:00 [queued]>
[2025-06-17T18:27:49.656+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_csv_to_hive.spark_ingest manual__2025-06-17T18:22:36.742697+00:00 [queued]>
[2025-06-17T18:27:49.657+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-06-17T18:27:49.669+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): spark_ingest> on 2025-06-17 18:22:36.742697+00:00
[2025-06-17T18:27:49.676+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1190) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-17T18:27:49.677+0000] {standard_task_runner.py:72} INFO - Started process 1191 to run task
[2025-06-17T18:27:49.676+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ingest_csv_to_hive', 'spark_ingest', 'manual__2025-06-17T18:22:36.742697+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/ETL_flow.py', '--cfg-path', '/tmp/tmpxpn_k2_1']
[2025-06-17T18:27:49.678+0000] {standard_task_runner.py:105} INFO - Job 16: Subtask spark_ingest
[2025-06-17T18:27:49.698+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-17T18:27:49.734+0000] {task_command.py:467} INFO - Running <TaskInstance: ingest_csv_to_hive.spark_ingest manual__2025-06-17T18:22:36.742697+00:00 [running]> on host b11ca03b7444
[2025-06-17T18:27:49.811+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_csv_to_hive' AIRFLOW_CTX_TASK_ID='spark_ingest' AIRFLOW_CTX_EXECUTION_DATE='2025-06-17T18:22:36.742697+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-17T18:22:36.742697+00:00'
[2025-06-17T18:27:49.812+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-06-17T18:27:49.827+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-06-17T18:27:49.828+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'set -o pipefail && spark-submit --master spark://spark-master:7077 --deploy-mode client /opt/***/code/stage.py --process-date 2025-06-17 2>&1']
[2025-06-17T18:27:49.839+0000] {subprocess.py:99} INFO - Output:
[2025-06-17T18:27:52.139+0000] {subprocess.py:106} INFO - 25/06/17 18:27:52 INFO SparkContext: Running Spark version 3.3.4
[2025-06-17T18:27:52.183+0000] {subprocess.py:106} INFO - 25/06/17 18:27:52 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-06-17T18:27:52.250+0000] {subprocess.py:106} INFO - 25/06/17 18:27:52 INFO ResourceUtils: ==============================================================
[2025-06-17T18:27:52.251+0000] {subprocess.py:106} INFO - 25/06/17 18:27:52 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-06-17T18:27:52.252+0000] {subprocess.py:106} INFO - 25/06/17 18:27:52 INFO ResourceUtils: ==============================================================
[2025-06-17T18:27:52.252+0000] {subprocess.py:106} INFO - 25/06/17 18:27:52 INFO SparkContext: Submitted application: CSV to Hive Tables - staging
[2025-06-17T18:27:52.267+0000] {subprocess.py:106} INFO - 25/06/17 18:27:52 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-06-17T18:27:52.273+0000] {subprocess.py:106} INFO - 25/06/17 18:27:52 INFO ResourceProfile: Limiting resource is cpu
[2025-06-17T18:27:52.274+0000] {subprocess.py:106} INFO - 25/06/17 18:27:52 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-06-17T18:27:52.310+0000] {subprocess.py:106} INFO - 25/06/17 18:27:52 INFO SecurityManager: Changing view acls to: ***
[2025-06-17T18:27:52.311+0000] {subprocess.py:106} INFO - 25/06/17 18:27:52 INFO SecurityManager: Changing modify acls to: ***
[2025-06-17T18:27:52.311+0000] {subprocess.py:106} INFO - 25/06/17 18:27:52 INFO SecurityManager: Changing view acls groups to:
[2025-06-17T18:27:52.312+0000] {subprocess.py:106} INFO - 25/06/17 18:27:52 INFO SecurityManager: Changing modify acls groups to:
[2025-06-17T18:27:52.313+0000] {subprocess.py:106} INFO - 25/06/17 18:27:52 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(***); groups with view permissions: Set(); users  with modify permissions: Set(***); groups with modify permissions: Set()
[2025-06-17T18:27:52.482+0000] {subprocess.py:106} INFO - 25/06/17 18:27:52 INFO Utils: Successfully started service 'sparkDriver' on port 37297.
[2025-06-17T18:27:52.503+0000] {subprocess.py:106} INFO - 25/06/17 18:27:52 INFO SparkEnv: Registering MapOutputTracker
[2025-06-17T18:27:52.530+0000] {subprocess.py:106} INFO - 25/06/17 18:27:52 INFO SparkEnv: Registering BlockManagerMaster
[2025-06-17T18:27:52.541+0000] {subprocess.py:106} INFO - 25/06/17 18:27:52 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-06-17T18:27:52.542+0000] {subprocess.py:106} INFO - 25/06/17 18:27:52 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-06-17T18:27:52.544+0000] {subprocess.py:106} INFO - 25/06/17 18:27:52 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-06-17T18:27:52.559+0000] {subprocess.py:106} INFO - 25/06/17 18:27:52 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-1a90af4f-5f81-4d0f-8084-66ef4c443a74
[2025-06-17T18:27:52.571+0000] {subprocess.py:106} INFO - 25/06/17 18:27:52 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-06-17T18:27:52.583+0000] {subprocess.py:106} INFO - 25/06/17 18:27:52 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-06-17T18:27:52.736+0000] {subprocess.py:106} INFO - 25/06/17 18:27:52 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-06-17T18:27:52.833+0000] {subprocess.py:106} INFO - 25/06/17 18:27:52 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
[2025-06-17T18:27:52.864+0000] {subprocess.py:106} INFO - 25/06/17 18:27:52 INFO TransportClientFactory: Successfully created connection to spark-master/172.28.0.4:7077 after 17 ms (0 ms spent in bootstraps)
[2025-06-17T18:27:52.927+0000] {subprocess.py:106} INFO - 25/06/17 18:27:52 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20250617182752-0002
[2025-06-17T18:27:52.928+0000] {subprocess.py:106} INFO - 25/06/17 18:27:52 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20250617182752-0002/0 on worker-20250617131755-172.28.0.9-39229 (172.28.0.9:39229) with 6 core(s)
[2025-06-17T18:27:52.930+0000] {subprocess.py:106} INFO - 25/06/17 18:27:52 INFO StandaloneSchedulerBackend: Granted executor ID app-20250617182752-0002/0 on hostPort 172.28.0.9:39229 with 6 core(s), 1024.0 MiB RAM
[2025-06-17T18:27:52.932+0000] {subprocess.py:106} INFO - 25/06/17 18:27:52 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 44233.
[2025-06-17T18:27:52.932+0000] {subprocess.py:106} INFO - 25/06/17 18:27:52 INFO NettyBlockTransferService: Server created on b11ca03b7444:44233
[2025-06-17T18:27:52.934+0000] {subprocess.py:106} INFO - 25/06/17 18:27:52 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-06-17T18:27:52.941+0000] {subprocess.py:106} INFO - 25/06/17 18:27:52 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, b11ca03b7444, 44233, None)
[2025-06-17T18:27:52.943+0000] {subprocess.py:106} INFO - 25/06/17 18:27:52 INFO BlockManagerMasterEndpoint: Registering block manager b11ca03b7444:44233 with 434.4 MiB RAM, BlockManagerId(driver, b11ca03b7444, 44233, None)
[2025-06-17T18:27:52.944+0000] {subprocess.py:106} INFO - 25/06/17 18:27:52 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, b11ca03b7444, 44233, None)
[2025-06-17T18:27:52.946+0000] {subprocess.py:106} INFO - 25/06/17 18:27:52 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, b11ca03b7444, 44233, None)
[2025-06-17T18:27:52.990+0000] {subprocess.py:106} INFO - 25/06/17 18:27:52 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20250617182752-0002/0 is now RUNNING
[2025-06-17T18:27:53.095+0000] {subprocess.py:106} INFO - 25/06/17 18:27:53 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2025-06-17T18:27:53.309+0000] {subprocess.py:106} INFO - 25/06/17 18:27:53 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-06-17T18:27:53.319+0000] {subprocess.py:106} INFO - 25/06/17 18:27:53 INFO SharedState: Warehouse path is 'file:/tmp/***tmpnkku_gyn/spark-warehouse'.
[2025-06-17T18:27:53.818+0000] {subprocess.py:106} INFO - 25/06/17 18:27:53 WARN SparkSession: Using an existing Spark session; only runtime SQL configurations will take effect.
[2025-06-17T18:27:55.211+0000] {subprocess.py:106} INFO - 25/06/17 18:27:55 INFO CoarseGrainedSchedulerBackend$DriverEndpoint: Registered executor NettyRpcEndpointRef(spark-client://Executor) (172.28.0.9:35722) with ID 0,  ResourceProfileId 0
[2025-06-17T18:27:55.286+0000] {subprocess.py:106} INFO - 25/06/17 18:27:55 INFO BlockManagerMasterEndpoint: Registering block manager 172.28.0.9:41045 with 434.4 MiB RAM, BlockManagerId(0, 172.28.0.9, 41045, None)
[2025-06-17T18:27:55.532+0000] {subprocess.py:106} INFO - 25/06/17 18:27:55 INFO HiveConf: Found configuration file null
[2025-06-17T18:27:55.538+0000] {subprocess.py:106} INFO - 25/06/17 18:27:55 INFO HiveUtils: Initializing HiveMetastoreConnection version 2.3.9 using Spark classes.
[2025-06-17T18:27:55.689+0000] {subprocess.py:106} INFO - 25/06/17 18:27:55 INFO HiveClientImpl: Warehouse location for Hive client (version 2.3.9) is file:/tmp/***tmpnkku_gyn/spark-warehouse
[2025-06-17T18:27:55.779+0000] {subprocess.py:106} INFO - 25/06/17 18:27:55 WARN HiveConf: HiveConf of name hive.stats.jdbc.timeout does not exist
[2025-06-17T18:27:55.780+0000] {subprocess.py:106} INFO - 25/06/17 18:27:55 WARN HiveConf: HiveConf of name hive.stats.retries.wait does not exist
[2025-06-17T18:27:55.780+0000] {subprocess.py:106} INFO - 25/06/17 18:27:55 INFO HiveMetaStore: 0: Opening raw store with implementation class:org.apache.hadoop.hive.metastore.ObjectStore
[2025-06-17T18:27:55.804+0000] {subprocess.py:106} INFO - 25/06/17 18:27:55 INFO ObjectStore: ObjectStore, initialize called
[2025-06-17T18:27:55.901+0000] {subprocess.py:106} INFO - 25/06/17 18:27:55 INFO Persistence: Property hive.metastore.integral.jdo.pushdown unknown - will be ignored
[2025-06-17T18:27:55.902+0000] {subprocess.py:106} INFO - 25/06/17 18:27:55 INFO Persistence: Property datanucleus.cache.level2 unknown - will be ignored
[2025-06-17T18:27:57.011+0000] {subprocess.py:106} INFO - 25/06/17 18:27:57 INFO ObjectStore: Setting MetaStore object pin classes with hive.metastore.cache.pinobjtypes="Table,StorageDescriptor,SerDeInfo,Partition,Database,Type,FieldSchema,Order"
[2025-06-17T18:27:58.385+0000] {subprocess.py:106} INFO - 25/06/17 18:27:58 INFO MetaStoreDirectSql: Using direct SQL, underlying DB is DERBY
[2025-06-17T18:27:58.387+0000] {subprocess.py:106} INFO - 25/06/17 18:27:58 INFO ObjectStore: Initialized ObjectStore
[2025-06-17T18:27:58.437+0000] {subprocess.py:106} INFO - 25/06/17 18:27:58 WARN ObjectStore: Version information not found in metastore. hive.metastore.schema.verification is not enabled so recording the schema version 2.3.0
[2025-06-17T18:27:58.438+0000] {subprocess.py:106} INFO - 25/06/17 18:27:58 WARN ObjectStore: setMetaStoreSchemaVersion called but recording version is disabled: version = 2.3.0, comment = Set by MetaStore UNKNOWN@172.28.0.18
[2025-06-17T18:27:58.451+0000] {subprocess.py:106} INFO - 25/06/17 18:27:58 WARN ObjectStore: Failed to get database default, returning NoSuchObjectException
[2025-06-17T18:27:58.586+0000] {subprocess.py:106} INFO - 25/06/17 18:27:58 INFO HiveMetaStore: Added admin role in metastore
[2025-06-17T18:27:58.589+0000] {subprocess.py:106} INFO - 25/06/17 18:27:58 INFO HiveMetaStore: Added public role in metastore
[2025-06-17T18:27:58.643+0000] {subprocess.py:106} INFO - 25/06/17 18:27:58 INFO HiveMetaStore: No user is added in admin role, since config is empty
[2025-06-17T18:27:58.695+0000] {subprocess.py:106} INFO - 25/06/17 18:27:58 INFO HiveMetaStore: 0: get_database: default
[2025-06-17T18:27:58.697+0000] {subprocess.py:106} INFO - 25/06/17 18:27:58 INFO audit: ugi=***	ip=unknown-ip-addr	cmd=get_database: default
[2025-06-17T18:27:58.708+0000] {subprocess.py:106} INFO - 25/06/17 18:27:58 INFO HiveMetaStore: 0: get_database: staging
[2025-06-17T18:27:58.709+0000] {subprocess.py:106} INFO - 25/06/17 18:27:58 INFO audit: ugi=***	ip=unknown-ip-addr	cmd=get_database: staging
[2025-06-17T18:27:58.711+0000] {subprocess.py:106} INFO - 25/06/17 18:27:58 WARN ObjectStore: Failed to get database staging, returning NoSuchObjectException
[2025-06-17T18:27:58.712+0000] {subprocess.py:106} INFO - 25/06/17 18:27:58 INFO HiveMetaStore: 0: get_database: staging
[2025-06-17T18:27:58.713+0000] {subprocess.py:106} INFO - 25/06/17 18:27:58 INFO audit: ugi=***	ip=unknown-ip-addr	cmd=get_database: staging
[2025-06-17T18:27:58.714+0000] {subprocess.py:106} INFO - 25/06/17 18:27:58 WARN ObjectStore: Failed to get database staging, returning NoSuchObjectException
[2025-06-17T18:27:58.728+0000] {subprocess.py:106} INFO - 25/06/17 18:27:58 INFO HiveMetaStore: 0: get_database: global_temp
[2025-06-17T18:27:58.733+0000] {subprocess.py:106} INFO - 25/06/17 18:27:58 INFO audit: ugi=***	ip=unknown-ip-addr	cmd=get_database: global_temp
[2025-06-17T18:27:58.734+0000] {subprocess.py:106} INFO - 25/06/17 18:27:58 WARN ObjectStore: Failed to get database global_temp, returning NoSuchObjectException
[2025-06-17T18:27:58.734+0000] {subprocess.py:106} INFO - 25/06/17 18:27:58 INFO HiveMetaStore: 0: create_database: Database(name:staging, description:, locationUri:file:/tmp/***tmpnkku_gyn/spark-warehouse/staging.db, parameters:{}, ownerName:***)
[2025-06-17T18:27:58.740+0000] {subprocess.py:106} INFO - 25/06/17 18:27:58 INFO audit: ugi=***	ip=unknown-ip-addr	cmd=create_database: Database(name:staging, description:, locationUri:file:/tmp/***tmpnkku_gyn/spark-warehouse/staging.db, parameters:{}, ownerName:***)
[2025-06-17T18:27:58.741+0000] {subprocess.py:106} INFO - 25/06/17 18:27:58 WARN ObjectStore: Failed to get database staging, returning NoSuchObjectException
[2025-06-17T18:27:58.742+0000] {subprocess.py:106} INFO - 25/06/17 18:27:58 INFO FileUtils: Creating directory if it doesn't exist: file:/tmp/***tmpnkku_gyn/spark-warehouse/staging.db
[2025-06-17T18:27:58.852+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-06-17T18:27:58.853+0000] {subprocess.py:106} INFO -   File "/opt/***/code/stage.py", line 84, in <module>
[2025-06-17T18:27:58.856+0000] {subprocess.py:106} INFO -     main()
[2025-06-17T18:27:58.856+0000] {subprocess.py:106} INFO -   File "/opt/***/code/stage.py", line 59, in main
[2025-06-17T18:27:58.858+0000] {subprocess.py:106} INFO -     if not path_exists(spark, hdfs_path):
[2025-06-17T18:27:58.858+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-06-17T18:27:58.859+0000] {subprocess.py:106} INFO -   File "/opt/***/code/stage.py", line 10, in path_exists
[2025-06-17T18:27:58.860+0000] {subprocess.py:106} INFO -     return fs.exists(p)
[2025-06-17T18:27:58.861+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^
[2025-06-17T18:27:58.861+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/py4j-0.10.9.5-src.zip/py4j/java_gateway.py", line 1321, in __call__
[2025-06-17T18:27:58.862+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 196, in deco
[2025-06-17T18:27:58.865+0000] {subprocess.py:106} INFO - pyspark.sql.utils.IllegalArgumentException: Wrong FS: hdfs://namenode:9000/landing/item/2025-06-17.csv, expected: file:///
[2025-06-17T18:27:58.899+0000] {subprocess.py:106} INFO - 25/06/17 18:27:58 INFO SparkContext: Invoking stop() from shutdown hook
[2025-06-17T18:27:58.906+0000] {subprocess.py:106} INFO - 25/06/17 18:27:58 INFO SparkUI: Stopped Spark web UI at http://b11ca03b7444:4040
[2025-06-17T18:27:58.908+0000] {subprocess.py:106} INFO - 25/06/17 18:27:58 INFO StandaloneSchedulerBackend: Shutting down all executors
[2025-06-17T18:27:58.908+0000] {subprocess.py:106} INFO - 25/06/17 18:27:58 INFO CoarseGrainedSchedulerBackend$DriverEndpoint: Asking each executor to shut down
[2025-06-17T18:27:58.925+0000] {subprocess.py:106} INFO - 25/06/17 18:27:58 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-06-17T18:27:58.939+0000] {subprocess.py:106} INFO - 25/06/17 18:27:58 INFO MemoryStore: MemoryStore cleared
[2025-06-17T18:27:58.940+0000] {subprocess.py:106} INFO - 25/06/17 18:27:58 INFO BlockManager: BlockManager stopped
[2025-06-17T18:27:58.946+0000] {subprocess.py:106} INFO - 25/06/17 18:27:58 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-06-17T18:27:58.948+0000] {subprocess.py:106} INFO - 25/06/17 18:27:58 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-06-17T18:27:58.958+0000] {subprocess.py:106} INFO - 25/06/17 18:27:58 INFO SparkContext: Successfully stopped SparkContext
[2025-06-17T18:27:58.958+0000] {subprocess.py:106} INFO - 25/06/17 18:27:58 INFO ShutdownHookManager: Shutdown hook called
[2025-06-17T18:27:58.960+0000] {subprocess.py:106} INFO - 25/06/17 18:27:58 INFO ShutdownHookManager: Deleting directory /tmp/spark-9be7393b-fc87-416f-adef-67293463fc7c/pyspark-2f7454b5-23fb-4845-9d27-5ab8dd77f86b
[2025-06-17T18:27:58.966+0000] {subprocess.py:106} INFO - 25/06/17 18:27:58 INFO ShutdownHookManager: Deleting directory /tmp/spark-9be7393b-fc87-416f-adef-67293463fc7c
[2025-06-17T18:27:58.969+0000] {subprocess.py:106} INFO - 25/06/17 18:27:58 INFO ShutdownHookManager: Deleting directory /tmp/spark-95fdabc2-f200-4d61-909f-752f034bf2c2
[2025-06-17T18:27:59.006+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-06-17T18:27:59.027+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-06-17T18:27:59.031+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=ingest_csv_to_hive, task_id=spark_ingest, run_id=manual__2025-06-17T18:22:36.742697+00:00, execution_date=20250617T182236, start_date=20250617T182749, end_date=20250617T182759
[2025-06-17T18:27:59.043+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-06-17T18:27:59.044+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 16 for task spark_ingest (Bash command failed. The command returned a non-zero exit code 1.; 1191)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-06-17T18:27:59.058+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-06-17T18:27:59.077+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-17T18:27:59.078+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
